### ISSUE TITLE
Invalid Decoding JoinRequest on mipsel

### ISSUE THREAD

**Issue by devleesch001** [chirpstack/chirpstack-mqtt-forwarder#52] opened 2024-02-26 13:42 UTC
Hello, 

I have an importante issue.

# What happened?

When the MQTT Forwarder deserialize JoinRequest Frame from Semtech UDP GWMP Frame, the MIC code is badly decoded.

For exemple the Semtech UDP GWMP JoinRequest have this MIC code `[1 192 29 90]` but after decoding by MQTT Forwarder have this `[1 192 28 90]`.

All my JoinRequest with MQTT Packet Forwarder are in MIC Error.

I am sur the problem appears during json deserialization, especially when decoding the payload in base64.

# How I found?

I added in code a debug print (only for me), before and After this line https://github.com/chirpstack/chirpstack-mqtt-forwarder/blob/8b2ed3d2a2bc1aab8d11a6a78a2d09929be983b9/src/backend/semtech_udp/mod.rs#L342C5-L342C51

Like this.

```rust
debug!("--- RAW UPLINK --- {:?}", data);

let pl = structs::PushData::from_slice(data)?;

debug!("--- DECODED PAYLOAD --- {:?}", pl.payload);

```

And I obtained this : 

RAW UDP GWMP Frame :
```hex
7b 22 72 78 70 6b 22 3a 5b 7b 22 6a 76 65 72 22 3a 31 2c 22 74 6d 73 74 22 3a 38 36 33 34 32 32 31 33 2c 22 63 68 61 6e 22 3a 37 2c 22 72 66 63 68 22 3a 31 2c 22 66 72 65 71 22 3a 38 36 38 2e 35 30 30 30 30 30 2c 22 6d 69 64 22 3a 20 30 2c 22 73 74 61 74 22 3a 31 2c 22 6d 6f 64 75 22 3a 22 4c 4f 52 41 22 2c 22 64 61 74 72 22 3a 22 53 46 31 32 42 57 31 32 35 22 2c 22 63 6f 64 72 22 3a 22 34 2f 35 22 2c 22 72 73 73 69 73 22 3a 2d 35 32 2c 22 6c 73 6e 72 22 3a 36 2e 32 2c 22 66 6f 66 66 22 3a 2d 37 34 37 36 2c 22 72 73 73 69 22 3a 2d 35 31 2c 22 73 69 7a 65 22 3a 32 33 2c 22 64 61 74 61 22 3a 22 41 41 49 41 41 41 44 77 37 4a 41 41 2b 52 30 78 46 67 48 73 6b 41 41 6c 4c 77 48 41 48 56 6f 3d 22 7d 5d 7d
```

Manual decoding I optain this Payload in JSON

```json
{"rxpk":[{"jver":1,"tmst":86342213,"chan":7,"rfch":1,"freq":868.500000,"mid": 0,"stat":1,"modu":"LORA","datr":"SF12BW125","codr":"4/5","rssis":-52,"lsnr":6.2,"foff":-7476,"rssi":-51,"size":23,"data":"AAIAAADw7JAA+R0xFgHskAAlLwHAHVo="}]}
```

This LoRaWAN DATA

```base64
AAIAAADw7JAA+R0xFgHskAAlLwHAHVo=
```

```hex
00 02 00 00 00 f0 ec 90 00 f9 1d 31 16 01 ec 90 00 25 2f 01 c0 1d 5a
```

Contain this MIC 

```
MIC : [1 192 29 90], 01c01d5a
```

But after `let pl = structs::PushData::from_slice(data)?;` 

When MQTT Forwarder deserialize the RAW UDP GWMP and decode the DATA of Payload Frame I obtaine this LoRaWAN Frame

```hex
00 02 00 00 00 f0 ec 90 00 f9 1d 31 16 01 ec 90 00 25 2f 01 c0 1c 5a
```

```
MIC : [1 192 28 90], 01c01c5a
```

The mic code does not correspond to the UDP frame.

GOOD `01c01d5a`, BAD `01c01c5a`

# Material

Gateway : `RAK7268CV2`

uname : `Linux RAK7268CV2 5.4.154 #0 Fri Nov 24 07:30:08 2023 mips GNU/Linux`

cpuinfo : 
```
system type		: MediaTek MT7628AN ver:1 eco:2
machine			: Rakwireless RAK636
processor		: 0
cpu model		: MIPS 24KEc V5.5
BogoMIPS		: 385.02
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa			: mips1 mips2 mips32r1 mips32r2
ASEs implemented	: mips16 dsp
Options implemented	: tlb 4kex 4k_cache prefetch mcheck ejtag llsc pindexed_dcache userlocal vint perf_cntr_intr_bit perf
shadow register sets	: 1
kscratch registers	: 0
package			: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available
```

OS : `WisGateOS_2.2.1_RAK` based on `OpenWRT 21.2` 
Toolchain : `make dist-mipsel-unknown-linux-musl`

**Comment by devleesch001** [comment] 2024-02-26 15:47
The problem seems to come from the base64 library, i made little poc to simple decode base64 string, follwoing oficial documention I obtain this

```rust
use base64::prelude::*;

fn main() {
    assert_eq!(BASE64_STANDARD.decode(b"+uwgVQA=").expect("panic"), b"\xFA\xEC\x20\x55\0");
    assert_eq!(BASE64_STANDARD.encode(b"\xFF\xEC\x20\x55\0"), "/+wgVQA=");
}
```

on my pc `x86_64-unknown-linux-musl` : 

```bash
./base64_test
echo $?
0
```

All it's ok

But on gateway with `mipsel-unknown-linux-musl` : 
```
./base64_test
thread 'main' panicked at src/main.rs:5:5:
assertion `left == right` failed
  left: [250, 236, 32, 84, 0]
 right: [250, 236, 32, 85, 0]

echo $?
101
```

The probleme should be comme from cross-rs, but I dont know.

**Comment by devleesch001** [comment] 2024-02-26 20:36
Maybe the compiler.

https://github.com/rust-lang/compiler-team/issues/648

Maybe we should develop our custom base64 decoding for this architecture

**Comment by brocaar** [comment] 2024-02-27 15:05
I can confirm that I was able to reproduce this issue. After compiling using the latest Rust toolchain, everything works as expected. I think this was a toolchain related issue. As mips has been moved to a tier 3 target, I have made the following change in the `Makefile`: https://github.com/chirpstack/chirpstack-mqtt-forwarder/commit/a9d9ebbc52157b15f710800c249b1f874e581b51

I'm creating a new release right now, which should be available shortly.

**Comment by brocaar** [comment] 2024-02-27 15:20
This was released as v4.2.0.

**Closed by brocaar** 2024-02-27 15:20 UTC

**Comment by devleesch001** [comment] 2024-02-27 15:26
I just compiled it and it works on my gateway.
Thanks you very much

**Comment by brocaar** [comment] 2024-03-11 14:38
Sorry, v4.2.1 re-introduces this issue because I downgraded the Rust toolchain because of nightly build issues (I forgot about that this might cause this issue). I will release a v4.2.2 shortly.
